### ISSUE TITLE
Eweb crosshair annoyingly snaps up and down while firing

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#105]
Even on latest smod, it's still annoying to aim the eweb because the crosshair won't stop moving. It should just stay in the raised state until you stop holding down mouse1.

inb4 ent rages at me for posting this

**Comment by entdark** [comment]
Lol I am not raged at all.
It's just useless issues since smod is not related to base_enhanced. And this repository turns into something ridiculous instead of normal development.
Being Sil I would just close anything but server-side issues.
Ask Sil to make an empty smod repository where you could post your issues there. And people use different client mods, not just smod fyi.

**Comment by deathsythe47** [comment]
And once again, ent is wrong about this being client-related. This recoil comes from the server.

Fixed in
https://github.com/deathsythe47/base_entranced/commit/7b1fea15ba2f8bf0f5f69ddff8f9280783119a23
https://github.com/deathsythe47/base_entranced/commit/1dce86275495c2a922b2786db4659fc03f4f42fd
