### ISSUE TITLE
Major bug found with g_floatingitems 0

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#106]
This only seems to happen on desert.

Set g_floatingitems 0
Grab droid part
Stand next to a wall or corner
Selfkill
Wait for droid part to return

You can no longer grab the droid part.

**Comment by deathsythe47** [comment]
I think the devs were aware of this bug, and instead of making a proper fix, they instead caused siege items to float. It's a crappy/lazy fix, but it indeed solved the bug. However, it also obviously added the classic retarded floating items behavior in siege.

**Comment by TheSil** [comment]
There just seemed to be a bug that physical entities were not linked to the world once they appeared inside solid object, so its position was incorrectly detected by engine (because of that could not be picked). Update above should fix it (not sure why github is showing that whole file has changed, 1 line was added :).

**Comment by deathsythe47** [comment]
Nice, it's fixed. Can you think of this causing any unforeseen bugs with entities that _shouldn't_ be linked to the world?

**Comment by deathsythe47** [comment]
Seems to be working fine with no problems.
