### ISSUE TITLE
Vehicle explosions do not properly credit the vehicle's killer

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#113]
-Spawn a swoop or ATST
-You and a friend stand near the swoop/ATST
-Damage it to zero
-It lights on fire
-It explodes
-You both die

You both get "died." message. Instead it should say "Padawan was killed by atst_killer" for everyone who died from the explosion. No matter who was piloting the vehicle, it should give credit for kills to whoever damaged the walker to 0hp.

BTW they knew about this bug...

```
//FIXME: does this give proper credit to the enemy who shot you down?

//FIXME: proper origin, MOD and attacker (for credit/death message)?  Get from vehicle?
```

BTW should make sure that fixing this doesn't cause bugs if ATST dies from natural causes (falling in pit, getting turreted, etc)

**Comment by TheSil** [comment]
I think current behaviour is as expected. The comment you found is probably just copy paste issue, because exactly same comment is mentioned in position where someone destroyes vehicle in which someone is inside. In that case it should indeed credit the shooter, but in case someone is just standing near by, i dont think that is intented.
