### ISSUE TITLE
Player blocking locked/enemy doors in siege ("door greening")

### ISSUE THREAD

**Issue by TheSil** [TheSil/base_enhanced#14]
In base this behaviour causes doors to be unlocked from the moment when enenmy player blocked the door. In base_enhanced this just takes damage from the player. This is understood to be useful feature for siege.

**Comment by TheSil** [comment]
I think this needs more investigation and is probably related to generally any mover object taking damage. It should be updated so that if it is locked kind of mover, it should follow the description above. Also consider taking gametype into account.

**Comment by deathsythe47** [comment]
Toggling this with a variable might be preferable, like sv_doorgreening or something, because door greening is generally acknowledged as an important tactic in siege.

Should default to base JK3 behavior, with the option to change to base_enhanced behavior.

**Comment by deathsythe47** [comment]
added cvar g_doorgreening in a7b2ac6b7bcc30218b43513c0052d0e1812675b9

the problem was your flag-in-door code.

however this might be preferable for some admins, even in siege mode, so i decided to make it a cvar instead of a gametype detection.

set to 0 = base_enhanced doors behavior (includes flag-in-door fix)
set to 1 = basejk3 doors behavior (no flag-in-door fix)

**Comment by TheSil** [comment]
The thing wasnt related to flags themselvs but to fix related to lifts/movers. I have reverted one of these fixes in 8819407b0b6857307d37a9387bb9c857378acf2d because i coudlnt reproduce the behaviour anyway, flags still seem to work fine with this (not jamming it), while greening of doors is working as well.
