### ISSUE TITLE
Missing message on joining team

### ISSUE THREAD

**Issue by Grab11** [TheSil/base_enhanced#55]
Siege missing message "Player X joined spectators/team red/team blue" in the middle of screen. 
Also migh be "Player X joined Team Imperial" instead of "Player X joined Team Red"

**Comment by TheSil** [comment]
This is for some reason disabled on purpose. It needs to be investigated how to get some reasonable team name to show, then it can be enabled. Unfortunately current siege maps only define team names such as "Siege1_Imperial", no other name is being available. So probably we will need to parse this string and show part after "_", question is how reliable is this approach in non standard maps.

**Comment by deathsythe47** [comment]
In the .siege file you can find the reasonable team names under the braces Teams { }

For hoth we get

``` Teams
{
    team1 @SIEGE_HOTH_TEAM1_IMPERIAL
    team2 @SIEGE_HOTH_TEAM2_REBEL
}
```

Because of the @ symbol at the beginning, this translates to a reasonable name in whatever language you have selected (English, German, French, or Spanish) as found in siege.str

For instance on Desert we have in German:

```
REFERENCE           DESE_TEAM2_MERCS
LANG_ENGLISH        "Mercs"
LANG_GERMAN         "Söldner"
```

However for custom maps this is not a problem(as far as I know!) as (most?)authors have simply written out the reasonable names in the .siege file, like nar shaddaa:

```
Teams
{
    team1 Rebel
    team2 Mercenary
}
```

I think the simplest solution, however, would just be "offense" and "defense," which in siege red=offense and blue=defense.

Btw you can see these names ingame by clicking "join" and then looking at the little text above the rebel/imp symbol, where you choose what team you want(above the class selection)

**Comment by TheSil** [comment]
Alright implemented first part, so team changes are now properly announced.

However team names are still red/blue, i have encountered issues when trying to use the names you proposed, because client game tries to translate it fails, because it looks for "SVGAME_@...." string instead of just "@...". I dont know how to make this work just by changes on server side, without touching client mod. So for now we have just red/blue team until we come up with better solution.

**Comment by deathsythe47** [comment]
Tried the build on elysium today and it's fine the way it is. I see no reason to worry about getting the "rebel" etc names. Think you can close this one...
