### ISSUE TITLE
New players can't connect to server during /pause

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#72]
Example:
Player lags out of game
Everyone /pauses so he can come back
Player attempts to connect to server and gets stuck at "awaiting snapshot"
Players ingame see "Padawan server command overflow"

**Comment by TheSil** [comment]
Yes this is a known issue, problem is fundamentally in how pause works. It constantly increments all timers game have stored (well apparently not all of them since we all still discovering some timers that do not increment...), and some of these timers affect data that are sent to client. This data are then transmitted and spam clients. Those clients that are connected to the server can handle these easily, they just process them and server can discard them. However with connecting clients, server has to buffer these commands until they actually finish connecting, and server simply does not have capacity to hold that many commands, so they overflow.

Few quick ideas:
- increasing command buffers (probably will be engine related but i havent looked at it)
- trying to find what commands cause this and try to do something with them (do not send them on each frame?)

**Comment by dpadgett** [comment]
you should be able to just not send the updates if a player's not fully
connected yet
other idea: don't send update if player has > X (10?) unacked server
commands sent

**Comment by TheSil** [comment]
Well i think the actual problem is that those commands are buffered and overflow on server side, no client side....

**Comment by dpadgett** [comment]
yeah that is what i meant.  do not even attempt to send to those clients
that are not fully connected, in gamecode.

**Comment by TheSil** [comment]
I think the server engine actually sends those, you change config string, engine sends it to all clients. 

Anyway i have found out that one recent change added large amount of configstring settings, so i reduced it to be done on 1 Hz rate, now it should be reasonable long time for connecting before command buffer overflows.
