### ISSUE TITLE
Obj complete sounds don't play for the final obj

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#93]
For example Hoth has 6 objectives. If you complete objs 1-5, you get "secondary objective complete" sound on offense and "the enemy has completed a secondary objective" sound on defense. However for obj 6, there is no sound, even though in the .siege file you can see that Ravensoft wanted to play "primary objective complete" and "the enemy has completed a primary objective." For some reason that sound is ignored.

Obviously client related.

**Comment by TheSil** [comment]
There are several issues here.

First, there are missing sounds for round complete in jka:
sound\chars\protocol\misc\40mom014.mp3
sound\chars\protocol\misc\40mom012.mp3

Second, server is only sending one objective/round message, so if objective happens to be final, it does not send it, and sends round complete instead. My guess is that its because otherwise it gets overwritten by client immediately (sound on announcer gets override), so you would only hear the second one anyway. This needs to be fixed on both sides, server and client. Server needs to send both, client needs to buffer the sound instead of just starting it. Also buffered sounds on client side are only running for 750 ms until they are override by next sound.

**Comment by deathsythe47** [comment]
Oh I didn't even know about those sounds. I think most siege maps don't have them.

I was actually talking about this:

```
sound_team1 "sound/chars/protocol/misc/siege1.mp3"
sound_team2 "sound/chars/protocol/misc/siege5.mp3"
```

Those sounds don't get played if objective is final. They do exist.

**Comment by entdark** [comment]
Where you got that magic 750 ms number? Never seen.

**Comment by TheSil** [comment]
There is probably much more you have never seen :) Look for 

```
cg.soundTime = cg.time + 750;
```

**Comment by entdark** [comment]
Oh, it's because you prolly have disabled OpenAL. DirectSound cannot mix the sounds on the same channel (both CHAN_ANNOUNCER) and just interrupts first. OpenAL or jaMME's DirectSound can mix them. Try to enable to test.
I just always can hear how announcer sounds get mixed. No any interruptions.
